### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by zack-bitcoin** [wirelessdreamer/joy2chord#1]
when using autogen.sh I get these errors:
```
configure.in:6: error: required file 'config/compile' not found
configure.in:6:   'automake --add-missing' can install 'compile'
configure.in:3: error: required file 'config/install-sh' not found
configure.in:3:   'automake --add-missing' can install 'install-sh'
configure.in:3: error: required file 'config/missing' not found
configure.in:3:   'automake --add-missing' can install 'missing'
src/Makefile.am: error: required file 'config/depcomp' not found
src/Makefile.am:   'automake --add-missing' can install 'depcomp'
```

Then when I try to make I get this error:
```
Makefile:347: recipe for target 'joy2chord.o' failed
make[2]: *** [joy2chord.o] Error 127
make[2]: Leaving directory '/home/zack/Hacking/joy2chord2/src'
Makefile:358: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/zack/Hacking/joy2chord2'
Makefile:299: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by wirelessdreamer** [comment]
depending on what flavor of linux your on, you'll need to install automake to satisfy those build dependencies. on debian its
`sudo apt-get install automake`

Its been an eternity since i've touched this. when I did a test build here it didn't compile for me, I made some updates and a new commit, its compiling now under wsl, but I don't have a linux machine handy right now to test with hardware. Let me know if it works or not for you. I'm going to try and make some time in the next week to build this on a linux machine and make sure it still works.

**Comment by zack-bitcoin** [comment]
I am in ubuntu. 
It says automake was already installed.

After pulling the new version of joy2chort, the error is a little different
```
configure.in:6: error: required file 'config/compile' not found
configure.in:6:   'automake --add-missing' can install 'compile'
configure.in:3: error: required file 'config/missing' not found
configure.in:3:   'automake --add-missing' can install 'missing'
src/Makefile.am: error: required file 'config/depcomp' not found
src/Makefile.am:   'automake --add-missing' can install 'depcomp'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
autoreconf: automake failed with exit status: 1
```

**Comment by zack-bitcoin** [comment]
the command `automake --add-missing` seems to have installed some dependencies I needed to compile this.

**Comment by zack-bitcoin** [comment]
Now I am stuck on this error when I try to run the compiled binary
```
Unable to open /dev/misc/uinput
Unable to open /dev/input/uinput
Unable to open /dev/uinput
Unable to open any uinput device: Permission denied
Please make sure the uinput module is loaded in your kernel
```

I am able to use the gamepad from other programs.

**Comment by wirelessdreamer** [comment]
I'm guessing from the permission denied message, that your user doesn't have permissions to the uinput device:

https://tkcheng.wordpress.com/2013/11/11/changing-uinput-device-permission/

this can be verified manually before and after by running cat on your uinput device file. ex: cat /dev/uinput
If that gives a permission error then the above blog post should help resolve it.

The other possible cause could be the uinput kernel module isn't loaded, but my guess is its permission related.

**Comment by zack-bitcoin** [comment]
This worked for me. 
I am able to type with my gamepad.
Thank you!

**Comment by wirelessdreamer** [comment]
Great :)
