### ISSUE TITLE
D-pad buttons

### ISSUE THREAD

**Issue by zack-bitcoin** [wirelessdreamer/joy2chord#2]
I am using a logitech F310 gamepad, and it would be nice if I could use some dpad buttons for my left hand instead of overloading my right hand.
I am looking through the code to try and make an update. 
If you have any advice to give, that would be great.

**Comment by wirelessdreamer** [comment]
In the process events function on line 930
`case JS_EVENT_BUTTON:`
we have a logic block for button presses
Looking at the kernel joystick api documentation: 
https://www.kernel.org/doc/Documentation/input/joystick-api.txt
it looks like we could add a logic block for JS_EVENT_AXIS, and handle everything in there.

Let me know if you other questions. I'd be glad to look at a pull request if you get to that point.

Unrelated to that, if you have any interest in making a short video of what you made and how its working for you I'd be glad to link it on the main page for you.

**Comment by zack-bitcoin** [comment]
I was able to get this to work, but I did it in a messy way.
I didn't set it up to use the config file. 
buttons 6 and 7 are duplicated onto my d-pad.
https://github.com/zack-bitcoin/joy2chord
Now I am very happy with how this is working.
Thanks for the help.

**Comment by wirelessdreamer** [comment]
sure thing, enjoy :)
